### ISSUE TITLE
npm-install error: Darwin 15.0.0

### ISSUE THREAD

**Issue by bk110w** [jbutko/AngularJS-Boilerplate#13]
## Snippet from Log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! angularjs-boilerplate@1.1.7 postinstall: `bower install --no-interactive --allow-root`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the angularjs-boilerplate@1.1.7 postinstall script 'bower install --no-interactive --allow-root'.
npm ERR! This is most likely a problem with the angularjs-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --no-interactive --allow-root
npm ERR! You can get their info via:
npm ERR!     npm owner ls angularjs-boilerplate

**Comment by bk110w** [comment]
Doh! I fixed my own problem - I updated to the most recent version of npm (npm -g install npm) and installed bower.

**Comment by jbutko** [comment]
Great, glad you found a solution. To be honest I thought it has something to do with `gulp-sass` or `gulp-image` because I had a lot of troubles during `npm install` with both of them.

**Comment by bk110w** [comment]
Thanks for the speedy response Jozef - truly my own fault this morning. The
boilerplate is great!

Ben Kusak
