### ISSUE TITLE
Sass file bug

### ISSUE THREAD

**Issue by emise** [jbutko/AngularJS-Boilerplate#15]
The boilerplate has a bug in the sass file - if you try to run `gulp` right after install, you'll get a sass compile failure. After some debugging I found that it's

``` javascript
Error: styles/modules/_alerts.scss
Error: ".alert-help" failed to @extend "%alert".
       The selector "%alert" was not found.
       Use "@extend %alert !optional" if the extend should be able to fail.
        on line 15 of styles/modules/_alerts.scss
```

Edit - made a pull request https://github.com/jbutko/AngularJS-Boilerplate/pull/16

**Comment by jbutko** [comment]
Fixed in PR #16 Closing.
