### ISSUE TITLE
lots of installation troubles

### ISSUE THREAD

**Issue by dave-mitchell** [jbutko/AngularJS-Boilerplate#18]
first ran into issues w/ the package lodash.assign when trying to "gulp build", and after installing that, I got:
[16:24:40] Error in plugin 'run-sequence(sass:build)'
Message:
    ENOENT, no such file or directory '/home/ubuntu/code/AngularJS-Boilerplate/node_modules/gulp-sass/node_modules/node-sass/vendor'

After creating that as an empty directory (last resort) I now get:
 Error: Missing binding /home/ubuntu/code/AngularJS-Boilerplate/node_modules/gulp-sass/node_modules/node-sass/vendor/linux-x64-11/binding.node

I'm assuming something didn't install correctly or there's some component missing.  I'm trying to use this project on a fresh generic Ubuntu 14.04 EC2 instance.

**Comment by PriyanshDwivedi** [comment]
You need to install 'node-sass' package manually. Run the below command to install it.
`npm install node-sass --save-dev`

After it is installed, run `gulp build`.

**Comment by jbutko** [comment]
@dave-mitchell yeah @PriyanshDwivedi is right, it's probably related to quite problematic `gulp-sass` package. I just published new version that might fix issues with `gulp-sass` so please delete your `node_modules` forlder in `AngularJS-boilerplate` folder, pull new version and try again if it works.
