### ISSUE TITLE
can not build the boilerplate

### ISSUE THREAD

**Issue by tanmoythander** [jbutko/AngularJS-Boilerplate#19]
The default code can't build itself. throws an error on the task 'usemin'

**Comment by deepaknasa** [comment]
Hi @tanmoythander Have you re-tried after updating your npm? Looks like there is versioning issue with the semver.js

**Comment by chukitow** [comment]
Same issue

**Comment by jbutko** [comment]
@tanmoythander @deepaknasa @chukitow I just published new version that might fix your issues with building the app. Please make a pull and try `npm install` again.

**Comment by tanmoythander** [comment]
Ok, i will try tomorrow, and I will let you know

**Comment by tanmoythander** [comment]
It's working fine now. Thank you so much.

**Comment by jbutko** [comment]
Great thanks for testing it out.
