### ISSUE TITLE
Refactoring Gulp file

### ISSUE THREAD

**Issue by gyss** [jbutko/AngularJS-Boilerplate#2]
Hi,
nice boilerplate ;)

Maybe you should use [gulp-load-plugins](https://www.npmjs.com/package/gulp-load-plugins) for having a cleaner gulp file.

**Comment by jbutko** [comment]
Hi, thanks. That's true, to be honest I wanted to rewrite it but was lazy :) But maybe I will do it in the future.

**Comment by jbutko** [comment]
Closing this one.
