### ISSUE TITLE
Cannot run install

### ISSUE THREAD

**Issue by roblawford** [jbutko/AngularJS-Boilerplate#20]
Hi there - 

Install fails on:

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.6.1
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angularjs-boilerplate@1.1.7 postinstall: `bower install --no-interactive --allow-root`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angularjs-boilerplate@1.1.7 postinstall script 'bower install --no-interactive --allow-root'.
npm ERR! This is most likely a problem with the angularjs-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --no-interactive --allow-root
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angularjs-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angularjs-boilerplate
npm ERR! There is likely additional logging output above.

This is from my debug:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@2.15.9
3 info using node@v4.6.1
4 verbose readDependencies loading dependencies from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\package.json
5 verbose install where, deps [ 'C:\\Users\\Rob\\Documents\\NetBeansProjects\\huyu-2017',
5 verbose install   [ 'angular-animate',
5 verbose install     'browser-sync',
5 verbose install     'connect',
5 verbose install     'connect-livereload',
5 verbose install     'del',
5 verbose install     'gulp',
5 verbose install     'gulp-angular-templatecache',
5 verbose install     'gulp-autoprefixer',
5 verbose install     'gulp-changed',
5 verbose install     'gulp-concat',
5 verbose install     'gulp-filter',
5 verbose install     'gulp-html-replace',
5 verbose install     'gulp-imagemin',
5 verbose install     'gulp-load-plugins',
5 verbose install     'gulp-minify-css',
5 verbose install     'gulp-minify-html',
5 verbose install     'gulp-notify',
5 verbose install     'gulp-rename',
5 verbose install     'gulp-rev',
5 verbose install     'gulp-sass',
5 verbose install     'gulp-size',
5 verbose install     'gulp-sourcemaps',
5 verbose install     'gulp-uglify',
5 verbose install     'gulp-uncss',
5 verbose install     'gulp-usemin',
5 verbose install     'opn',
5 verbose install     'run-sequence',
5 verbose install     'serve-index',
5 verbose install     'serve-static',
5 verbose install     'tiny-lr',
5 verbose install     'watch' ] ]
6 verbose install where, peers [ 'C:\\Users\\Rob\\Documents\\NetBeansProjects\\huyu-2017', [] ]
7 verbose installManyTop reading for lifecycle C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\package.json
8 info preinstall angularjs-boilerplate@1.1.7
9 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\angular-animate\package.json
10 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\browser-sync\package.json
11 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\connect\package.json
12 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\connect-livereload\package.json
13 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\del\package.json
14 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp\package.json
15 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-angular-templatecache\package.json
16 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-autoprefixer\package.json
17 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-changed\package.json
18 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-concat\package.json
19 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-filter\package.json
20 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-html-replace\package.json
21 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-imagemin\package.json
22 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-load-plugins\package.json
23 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-minify-css\package.json
24 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-minify-html\package.json
25 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-notify\package.json
26 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-rename\package.json
27 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-rev\package.json
28 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-sass\package.json
29 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-size\package.json
30 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-sourcemaps\package.json
31 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-uglify\package.json
32 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-uncss\package.json
33 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-usemin\package.json
34 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\opn\package.json
35 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\run-sequence\package.json
36 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\serve-index\package.json
37 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\serve-static\package.json
38 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\tiny-lr\package.json
39 verbose installManyTop reading scoped package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\watch\package.json
40 info package.json browser-sync@1.9.2 No license field.
41 info package.json gulp-minify-css@1.2.4 No repository field.
42 info package.json gulp-minify-html@0.1.8 No license field.
43 info package.json gulp-notify@2.2.0 No license field.
44 info package.json gulp-rename@1.2.2 No license field.
45 info package.json watch@0.13.0 No license field.
46 verbose readDependencies loading dependencies from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\package.json
47 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\angular-animate\package.json
48 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\browser-sync\package.json
49 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\connect\package.json
50 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\connect-livereload\package.json
51 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\del\package.json
52 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp\package.json
53 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-angular-templatecache\package.json
54 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-autoprefixer\package.json
55 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-changed\package.json
56 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-concat\package.json
57 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-filter\package.json
58 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-html-replace\package.json
59 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-imagemin\package.json
60 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-load-plugins\package.json
61 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-minify-css\package.json
62 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-minify-html\package.json
63 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-notify\package.json
64 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-rename\package.json
65 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-rev\package.json
66 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-sass\package.json
67 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-size\package.json
68 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-sourcemaps\package.json
69 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-uglify\package.json
70 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-uncss\package.json
71 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\gulp-usemin\package.json
72 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\opn\package.json
73 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\run-sequence\package.json
74 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\serve-index\package.json
75 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\serve-static\package.json
76 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\tiny-lr\package.json
77 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\watch\package.json
78 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\browser-sync\package.json
79 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\browser-sync.cmd\package.json
80 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\gulp\package.json
81 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\gulp.cmd\package.json
82 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\opn\package.json
83 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\opn.cmd\package.json
84 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\watch\package.json
85 verbose targetResolver reading package data from C:\Users\Rob\Documents\NetBeansProjects\huyu-2017\node_modules\.bin\watch.cmd\package.json
86 verbose already installed skipping gulp@^3.8.10 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
87 verbose already installed skipping gulp-angular-templatecache@^1.6.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
88 verbose already installed skipping gulp-autoprefixer@^2.1.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
89 verbose already installed skipping gulp-changed@^1.1.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
90 verbose already installed skipping gulp-concat@^2.4.3 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
91 verbose already installed skipping gulp-filter@^2.0.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
92 verbose already installed skipping gulp-html-replace@^1.4.4 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
93 verbose already installed skipping gulp-imagemin@^3.1.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
94 verbose already installed skipping gulp-load-plugins@^0.10.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
95 verbose already installed skipping gulp-minify-css@^1.2.4 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
96 verbose already installed skipping gulp-minify-html@^0.1.8 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
97 verbose already installed skipping gulp-notify@^2.1.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
98 verbose already installed skipping gulp-rename@^1.2.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
99 verbose already installed skipping gulp-rev@^3.0.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
100 verbose already installed skipping gulp-sass@^2.1.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
101 verbose already installed skipping gulp-size@^1.2.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
102 verbose already installed skipping gulp-sourcemaps@^1.3.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
103 verbose already installed skipping gulp-uglify@^1.1.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
104 verbose already installed skipping gulp-uncss@^1.0.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
105 verbose already installed skipping gulp-usemin@^0.3.11 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
106 verbose already installed skipping opn@^1.0.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
107 verbose already installed skipping run-sequence@^1.0.2 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
108 verbose already installed skipping serve-index@^1.5.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
109 verbose already installed skipping serve-static@^1.7.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
110 verbose already installed skipping tiny-lr@^0.1.4 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
111 verbose already installed skipping watch@^0.13.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
112 verbose already installed skipping angular-animate@^1.6.3 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
113 verbose already installed skipping browser-sync@^1.9.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
114 verbose already installed skipping connect@^3.3.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
115 verbose already installed skipping connect-livereload@^0.5.0 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
116 verbose already installed skipping del@^1.1.1 C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
117 silly install resolved []
118 info build C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
119 info linkStuff angularjs-boilerplate@1.1.7
120 silly linkStuff angularjs-boilerplate@1.1.7 has C:\Users\Rob\Documents\NetBeansProjects as its parent node_modules
121 verbose linkBins angularjs-boilerplate@1.1.7
122 verbose linkMans angularjs-boilerplate@1.1.7
123 verbose rebuildBundles angularjs-boilerplate@1.1.7
124 verbose rebuildBundles [ '.bin',
124 verbose rebuildBundles   'angular-animate',
124 verbose rebuildBundles   'browser-sync',
124 verbose rebuildBundles   'connect',
124 verbose rebuildBundles   'connect-livereload',
124 verbose rebuildBundles   'del',
124 verbose rebuildBundles   'gulp',
124 verbose rebuildBundles   'gulp-angular-templatecache',
124 verbose rebuildBundles   'gulp-autoprefixer',
124 verbose rebuildBundles   'gulp-changed',
124 verbose rebuildBundles   'gulp-concat',
124 verbose rebuildBundles   'gulp-filter',
124 verbose rebuildBundles   'gulp-html-replace',
124 verbose rebuildBundles   'gulp-imagemin',
124 verbose rebuildBundles   'gulp-load-plugins',
124 verbose rebuildBundles   'gulp-minify-css',
124 verbose rebuildBundles   'gulp-minify-html',
124 verbose rebuildBundles   'gulp-notify',
124 verbose rebuildBundles   'gulp-rename',
124 verbose rebuildBundles   'gulp-rev',
124 verbose rebuildBundles   'gulp-sass',
124 verbose rebuildBundles   'gulp-size',
124 verbose rebuildBundles   'gulp-sourcemaps',
124 verbose rebuildBundles   'gulp-uglify',
124 verbose rebuildBundles   'gulp-uncss',
124 verbose rebuildBundles   'gulp-usemin',
124 verbose rebuildBundles   'opn',
124 verbose rebuildBundles   'run-sequence',
124 verbose rebuildBundles   'serve-index',
124 verbose rebuildBundles   'serve-static',
124 verbose rebuildBundles   'tiny-lr',
124 verbose rebuildBundles   'watch' ]
125 info install angularjs-boilerplate@1.1.7
126 info postinstall angularjs-boilerplate@1.1.7
127 verbose unsafe-perm in lifecycle true
128 info angularjs-boilerplate@1.1.7 Failed to exec postinstall script
129 verbose stack Error: angularjs-boilerplate@1.1.7 postinstall: `bower install --no-interactive --allow-root`
129 verbose stack Exit status 1
129 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
129 verbose stack     at emitTwo (events.js:87:13)
129 verbose stack     at EventEmitter.emit (events.js:172:7)
129 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
129 verbose stack     at emitTwo (events.js:87:13)
129 verbose stack     at ChildProcess.emit (events.js:172:7)
129 verbose stack     at maybeClose (internal/child_process.js:829:16)
129 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
130 verbose pkgid angularjs-boilerplate@1.1.7
131 verbose cwd C:\Users\Rob\Documents\NetBeansProjects\huyu-2017
132 error Windows_NT 10.0.14393
133 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
134 error node v4.6.1
135 error npm  v2.15.9
136 error code ELIFECYCLE
137 error angularjs-boilerplate@1.1.7 postinstall: `bower install --no-interactive --allow-root`
137 error Exit status 1
138 error Failed at the angularjs-boilerplate@1.1.7 postinstall script 'bower install --no-interactive --allow-root'.
138 error This is most likely a problem with the angularjs-boilerplate package,
138 error not with npm itself.
138 error Tell the author that this fails on your system:
138 error     bower install --no-interactive --allow-root
138 error You can get information on how to open an issue for this project with:
138 error     npm bugs angularjs-boilerplate
138 error Or if that isn't available, you can get their info via:
138 error
138 error     npm owner ls angularjs-boilerplate
138 error There is likely additional logging output above.
139 verbose exit [ 1, true ]

Thanks.
Rob

**Comment by jbutko** [comment]
Looks like some issue with `bower` Do you have it installed globally? I just published new version with refactored npm/gulp tasks please try the new version if it solves your issue.
