### ISSUE TITLE
Build version error: angularlibs.js:2 Error: [$injector:unpr] Unknown provider: eProvider

### ISSUE THREAD

**Issue by heymynameisrob** [jbutko/AngularJS-Boilerplate#21]
Getting this error when running build version. Also views folder doesn't copy over to build. Help.

**Comment by jbutko** [comment]
Hard to tell but it looks like it might be a problem with dependency injection. Please double check your controllers/factories/services and check if your dependencies in `$inject` are in same order as in main controller/service function. Something along this way: https://github.com/jbutko/AngularJS-Boilerplate/blob/master/app/controller.js#L14

Regarding problem with `view` folder - all `html` files are concatenated into `templates.js` file with the help of `$templateCache` service. Please check if it is generated in `_build/js` folder and if the file is loaded in `index.html` file.

**Comment by heymynameisrob** [comment]
Sweet sorted it. Still not luck with the $templateCache. The file exists but when loaded doesn't seem to work. 

Error: [$compile:tpload] Failed to load template: views/home.html
