### ISSUE TITLE
Why dont use 1.5.x or later Angularjs version?

### ISSUE THREAD

**Issue by matheusggds** [jbutko/AngularJS-Boilerplate#22]
Angularjs is in 1.6.x version, and on 1.5.x they launched component stuffs... Dont u have interesent on? I liked your code, but run on 1.3.x is a lack of potential... have u a reason?

**Comment by jbutko** [comment]
That's simple, when I put it together there were neither 1.5.x nor component stuff. And now I do not have time to upgrade it to be honest.

However I have you covered - I also released MEAN stack boilerplate entitled [ExpressJS-Socket.IO-AngularJS-Boilerplate](https://github.com/jbutko/ExpressJS-Socket.IO-AngularJS-Boilerplate/tree/master/client) - the client part is based on AngularJS-Boilerplate and is component based with Angular 1.6.1 and UI Router 1 beta. Check that out here: https://github.com/jbutko/ExpressJS-Socket.IO-AngularJS-Boilerplate/tree/master/client

**Comment by matheusggds** [comment]
Thanks man, i was searching some project like this... using the most patterns, and not that complex. I will clone it and adjust for me, because i need to make a simple test for a job that i really want to get in. Is just a simple Products page, where u must me able do add, edit, and exclude products in the cart, i studied a lot, and i want to do it the best way i can.

I know u have no time, but if u could just take a look, I would be really greatfull.

Thanks buddy.
