### ISSUE TITLE
Angular UI router

### ISSUE THREAD

**Issue by Kaoschuks** [jbutko/AngularJS-Boilerplate#27]
I want to use angular ui router instead but when I reload the page I get an error not found if am on any page if not the root

**Comment by jbutko** [comment]
@Kaoschuks Please use this one: https://github.com/jbutko/ExpressJS-Socket.IO-AngularJS-Boilerplate/tree/master/client

It's basically same boilerplate as `AngularJS-Boilerplate`, but with Components (angular 1.6.1) and instead of angular-router I used Angular UI Router v1.

**Comment by Kaoschuks** [comment]
THANKS BOSS
