### ISSUE TITLE
Project added to comparison

### ISSUE THREAD

**Issue by dancancro** [jbutko/AngularJS-Boilerplate#4]
Hi,

I have added this project to my comparison of such things that one can use to get started making an app.  A column for this project is located at the far right of the spreadsheet you can find with [this](http://www.dancancro.com/comparison-of-angularjs-application-starters) link.

If you would like to help fill in the details about this project's attributes, let me know and I will add you to the editor list.

**Comment by jbutko** [comment]
Hi Dan, your project looks really useful, keep working on it. Though I do not have much time to fill details, I am quite busy now. Feel free to add details yourself or remove it from the list if you want. Maybe when I will have some spare time in the future I will contact you. Thanks.
